## MYSQL CONFIG
spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://nutee.cmwlqxe5se7d.ap-northeast-2.rds.amazonaws.com:3306/s_market?useUnicode=true&characterEncoding=UTF-8
 #   url: jdbc:mysql://127.0.0.1:3306/smarket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://127.0.0.1:3306/s_market?useUnicode=true&characterEncoding=UTF-8
    username: nutee
    password: since2012!
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
## AWS S3
cloud:
  aws:
    credentials:
      accessKey: AKIAYFYYWBMOY2RCK64P
      secretKey: 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
    s3:
      bucket: nutee-storage
      cloudFront: d3hcd6jhmx6a52.cloudfront.net
    region:
      static: ap-northeast-2
    stack:
      auto: false

